org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# Minecraft / NeoForge

minecraft_version=26.2
minecraft_version_range=[26.2]

neo_version=26.2.0.48-beta


# Mod Properties

mod_id=betterspawn
mod_name=BetterSpawn
mod_license=All Rights Reserved
mod_version=1.0.0-26.2-neo

mod_group_id=bandit_bytes_better_spawn

mod_authors=Bandit-Bytes
mod_description=Mod that fixes the /setworldspawn roof issues!