org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=betterspawn
mod_name=BetterSpawn
mod_license=All Rights Reserved
mod_version=1.0.2-1.20.1-forge
mod_group_id=bandit_bytes_better_spawn
mod_authors=Bandit-Bytes
mod_description= Mod that fixes /setworldspawn!
